@echo off
echo Starting HR System...
echo.
echo Starting Backend Server in new window...
start "HR Backend" cmd /c start-backend.bat
echo.
echo Waiting 3 seconds for backend to initialize...
timeout /t 3 /nobreak >nul
echo.
echo Starting Frontend Server in new window...
start "HR Frontend" cmd /c start-frontend.bat
echo.
echo Both servers are starting...
echo Backend: http://localhost:5001
echo Frontend: http://localhost:3000
echo.
echo Press any key to close this window...
pause 